'use strict';
// Historical questions avoid changing season-by-season records.
const bank = [
 {level:0,category:'THE LEGENDS',q:'Which NBA legend is known as “His Airness”?',a:['Kobe Bryant','Michael Jordan','LeBron James','Vince Carter'],c:1,f:'Michael Jordan’s gravity-defying game earned him the nickname “His Airness.”'},
 {level:0,category:'TEAM CULTURE',q:'Which team plays its home games at Madison Square Garden?',a:['Brooklyn Nets','Boston Celtics','New York Knicks','Philadelphia 76ers'],c:2,f:'The New York Knicks call Madison Square Garden home.'},
 {level:0,category:'THE FUNDAMENTALS',q:'How many points is a shot from beyond the three-point arc worth?',a:['One','Two','Three','Four'],c:2,f:'A successful field goal from beyond the arc is worth three points.'},
 {level:0,category:'THE LEGENDS',q:'Which player was nicknamed “The Black Mamba”?',a:['Allen Iverson','Kobe Bryant','Shaquille O’Neal','Dwyane Wade'],c:1,f:'Kobe Bryant adopted the Black Mamba nickname and made Mamba Mentality famous.'},
 {level:0,category:'TEAM CULTURE',q:'Which NBA franchise is based in Miami?',a:['Magic','Hawks','Heat','Pelicans'],c:2,f:'The Miami Heat joined the NBA in 1988.'},
 {level:0,category:'THE FUNDAMENTALS',q:'How many players from each team are on the court during regular play?',a:['Four','Five','Six','Seven'],c:1,f:'Basketball is played five-on-five.'},
 {level:0,category:'THE LEGENDS',q:'Which player is best known as “King James”?',a:['James Harden','LeBron James','James Worthy','Chris Paul'],c:1,f:'LeBron James has carried the “King James” nickname since his early career.'},
 {level:0,category:'TEAM CULTURE',q:'Which team is associated with the nickname “Dub Nation”?',a:['Dallas Mavericks','Denver Nuggets','Golden State Warriors','Chicago Bulls'],c:2,f:'“Dubs” comes from the W in Warriors, giving their fans the name Dub Nation.'},
 {level:1,category:'FINALS HISTORY',q:'Which team erased a 3–1 deficit to win the 2016 NBA Finals?',a:['Golden State Warriors','Cleveland Cavaliers','San Antonio Spurs','Miami Heat'],c:1,f:'Cleveland won three straight games to claim its first NBA title in 2016.'},
 {level:1,category:'THE LEGENDS',q:'Which player scored 81 points in a game against Toronto in 2006?',a:['Tracy McGrady','Allen Iverson','Kobe Bryant','Kevin Durant'],c:2,f:'Kobe Bryant scored 81 points against the Raptors on January 22, 2006.'},
 {level:1,category:'DRAFT NIGHT',q:'Which team drafted Dirk Nowitzki before trading him to Dallas in 1998?',a:['Milwaukee Bucks','Phoenix Suns','Boston Celtics','Sacramento Kings'],c:0,f:'Milwaukee drafted Nowitzki ninth overall, then traded him to Dallas.'},
 {level:1,category:'THE FUNDAMENTALS',q:'How long is a regulation quarter in the NBA?',a:['10 minutes','12 minutes','15 minutes','8 minutes'],c:1,f:'Four 12-minute quarters make up the NBA’s 48-minute regulation game.'},
 {level:1,category:'THE LEGENDS',q:'Who was nicknamed “The Answer”?',a:['Paul Pierce','Allen Iverson','Ray Allen','Steve Nash'],c:1,f:'Allen Iverson, the 2001 MVP, was known as “The Answer.”'},
 {level:1,category:'FINALS HISTORY',q:'Who won the NBA championship in the 1995–96 season?',a:['Seattle SuperSonics','Houston Rockets','Chicago Bulls','Utah Jazz'],c:2,f:'The 72-win Chicago Bulls defeated Seattle in the 1996 NBA Finals.'},
 {level:1,category:'TEAM CULTURE',q:'Which city did the Thunder franchise play in before Oklahoma City?',a:['Vancouver','Seattle','San Diego','Kansas City'],c:1,f:'The Seattle SuperSonics relocated to Oklahoma City in 2008.'},
 {level:1,category:'THE LEGENDS',q:'Which center was famous for his “skyhook” shot?',a:['Hakeem Olajuwon','Patrick Ewing','Kareem Abdul-Jabbar','David Robinson'],c:2,f:'Kareem Abdul-Jabbar’s skyhook became one of basketball’s most iconic shots.'},
 {level:2,category:'NBA HISTORY',q:'Who recorded the first officially recognized quadruple-double in NBA history?',a:['David Robinson','Nate Thurmond','Hakeem Olajuwon','Alvin Robertson'],c:1,f:'Nate Thurmond recorded 22 points, 14 rebounds, 13 assists and 12 blocks in 1974.'},
 {level:2,category:'FINALS HISTORY',q:'Who won Finals MVP in 1969 despite playing for the losing team?',a:['Wilt Chamberlain','Elgin Baylor','Jerry West','Bill Russell'],c:2,f:'Jerry West won the inaugural Finals MVP award as the Lakers lost to Boston.'},
 {level:2,category:'DRAFT NIGHT',q:'Who was the first overall pick in the 1984 NBA Draft?',a:['Michael Jordan','Sam Bowie','Charles Barkley','Hakeem Olajuwon'],c:3,f:'Houston selected Hakeem Olajuwon first; Michael Jordan was selected third.'},
 {level:2,category:'NBA HISTORY',q:'Which player won the NBA’s first-ever Slam Dunk Contest in 1984?',a:['Dominique Wilkins','Julius Erving','Larry Nance','Michael Jordan'],c:2,f:'Phoenix forward Larry Nance won the NBA’s inaugural dunk contest.'},
 {level:2,category:'THE LEGENDS',q:'Who was the first unanimous NBA MVP?',a:['Michael Jordan','LeBron James','Stephen Curry','Shaquille O’Neal'],c:2,f:'Stephen Curry received every first-place MVP vote in 2016.'},
 {level:2,category:'FINALS HISTORY',q:'Which team won the 1977 NBA championship?',a:['Portland Trail Blazers','Philadelphia 76ers','Washington Bullets','Boston Celtics'],c:0,f:'Bill Walton led Portland past Philadelphia for the 1977 championship.'},
 {level:2,category:'NBA HISTORY',q:'Which player recorded 30 assists in a single game in 1990?',a:['John Stockton','Magic Johnson','Scott Skiles','Isiah Thomas'],c:2,f:'Orlando’s Scott Skiles dished out 30 assists against Denver on December 30, 1990.'},
 {level:2,category:'THE LEGENDS',q:'Which player was named both MVP and Defensive Player of the Year in 1994?',a:['David Robinson','Hakeem Olajuwon','Michael Jordan','Shaquille O’Neal'],c:1,f:'Hakeem Olajuwon also added a championship and Finals MVP in his remarkable 1994 season.'}
];
const $ = id => document.getElementById(id);
let questions=[], index=0, score=0, streak=0, bestStreak=0, correctCount=0, locked=true, clock=null, deadline=0, history=[], soundEnabled=false, audioContext;
let highScore=0;
try { highScore=Number(localStorage.getItem('full-court-best'))||0; } catch {}
$('high-score').innerHTML=`${highScore} <small>points</small>`;
$('year').textContent=new Date().getFullYear();
function shuffle(items){const result=[...items];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]];}return result;}
function tone(correct){if(!soundEnabled)return;try{audioContext ||= new (window.AudioContext||window.webkitAudioContext)();audioContext.resume();const osc=audioContext.createOscillator(),gain=audioContext.createGain();osc.connect(gain);gain.connect(audioContext.destination);osc.frequency.setValueAtTime(correct?660:190,audioContext.currentTime);osc.frequency.exponentialRampToValueAtTime(correct?990:100,audioContext.currentTime+.16);gain.gain.setValueAtTime(.055,audioContext.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.23);osc.start();osc.stop(audioContext.currentTime+.25);}catch{}}
function progress(){ $('progress').innerHTML=Array.from({length:12},(_,i)=>`<i class="${history[i]===true?'correct':history[i]===false?'wrong':i===index&&!locked?'active':''}"></i>`).join('');$('progress-label').textContent=`${history.length} / 12`;}
function updateScore(){ $('score').textContent=String(score).padStart(4,'0');$('streak').innerHTML=`${streak} <small>in a row</small>`;}
function start(){clearInterval(clock);questions=[0,1,2].flatMap(level=>shuffle(bank.filter(q=>q.level===level)).slice(0,4).map(q=>{const choices=shuffle(q.a.map((text,i)=>({text,correct:i===q.c})));return {...q,choices};}));index=score=streak=bestStreak=correctCount=0;history=[];$('welcome').hidden=true;$('results').hidden=true;$('play').hidden=false;$('live-label').textContent='GAME ON';updateScore();showQuestion();}
function showQuestion(){locked=false;const q=questions[index];$('round-label').textContent=`QUESTION ${String(index+1).padStart(2,'0')} OF 12`;$('difficulty').textContent=['ROOKIE','ALL-STAR','LEGEND'][q.level];$('difficulty').dataset.level=q.level;$('category').textContent=q.category;$('question').textContent=q.q;$('answers').replaceChildren();q.choices.forEach((answer,i)=>{const button=document.createElement('button');button.className='answer';button.innerHTML=`<span class="key">${String.fromCharCode(65+i)}</span><span></span>`;button.lastElementChild.textContent=answer.text;button.addEventListener('click',()=>answerQuestion(i));$('answers').append(button);});$('feedback').textContent='';$('feedback').className='feedback';$('next').hidden=true;$('next').textContent=index===11?'SEE MY RESULTS →':'NEXT QUESTION →';deadline=performance.now()+20000;tick();clock=setInterval(tick,100);progress();$('question').focus({preventScroll:true});}
function tick(){if(locked)return;const remaining=Math.max(0,deadline-performance.now());$('timer').innerHTML=`${Math.ceil(remaining/1000)}<span>s</span>`;$('timer').style.color=remaining<=5000?'#d95c2a':'';$('timer-bar').style.width=`${remaining/200}%`;if(remaining<=0)answerQuestion(-1);}
function answerQuestion(choice){if(locked)return;if(choice!==-1&&performance.now()>=deadline){answerQuestion(-1);return;}locked=true;clearInterval(clock);const q=questions[index],correct=choice>=0&&q.choices[choice].correct;history.push(correct);let points=0;if(correct){streak++;correctCount++;bestStreak=Math.max(streak,bestStreak);points=100+q.level*50+(streak-1)*25;score+=points;}else streak=0;[...$('answers').children].forEach((button,i)=>{button.disabled=true;if(q.choices[i].correct)button.classList.add('correct');else if(i===choice)button.classList.add('incorrect');});$('feedback').className=`feedback ${correct?'success':'error'}`;$('feedback').textContent=`${correct?`Nice shot! +${points} points.`:choice===-1?'Shot clock violation!':'Off the mark.'} ${q.f}`;$('next').hidden=false;updateScore();progress();tone(correct);$('next').focus({preventScroll:true});}
function finish(){clearInterval(clock);$('play').hidden=true;$('results').hidden=false;$('live-label').textContent='GAME COMPLETE';$('round-label').textContent='THAT’S THE FINAL BUZZER';$('final-score').textContent=score.toLocaleString();$('accuracy').textContent=`${Math.round(correctCount/12*100)}%`;$('best-streak').textContent=bestStreak;const title=correctCount>=10?'Hall of fame material.':correctCount>=7?'An All-Star performance.':correctCount>=4?'You’ve got game.':'Back to the practice court.';$('result-title').textContent=title;const newBest=score>highScore;if(newBest){highScore=score;try{localStorage.setItem('full-court-best',String(highScore));}catch{}$('high-score').innerHTML=`${highScore} <small>points</small>`;}$('result-copy').textContent=`You hit ${correctCount} of 12 shots. ${newBest?'A new personal best! ':''}Ready for another run?`;$('replay').focus({preventScroll:true});}
$('start').addEventListener('click',start);$('replay').addEventListener('click',start);$('next').addEventListener('click',()=>{index++;if(index>=12)finish();else showQuestion();});$('sound').addEventListener('click',()=>{soundEnabled=!soundEnabled;$('sound').setAttribute('aria-pressed',soundEnabled);$('sound').setAttribute('aria-label',soundEnabled?'Disable sound':'Enable sound');$('sound').innerHTML=`♫ <span>SOUND ${soundEnabled?'ON':'OFF'}</span>`;if(soundEnabled)tone(true);});document.addEventListener('keydown',e=>{if(!locked&&!e.repeat&&/^[1-4]$/.test(e.key)){e.preventDefault();answerQuestion(Number(e.key)-1);}});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&!locked)tick();});progress();
